spring:
  profiles:
    active:
      - dev
---
info:
  pwd:
    test: this is dev 19-10-02
spring:
  profiles: dev
server:
  port: 3355
---
spring:
  profiles: test
info:
  pwd:
    test: this is test
